---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(5)

data("rest_inspec") 

rest_inspec = 
  rest_inspec %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>%
  sample_n(5000)
```


Column {data-width=550}
-----------------------------------------------------------------------

### Bar Graph: Distribution of Restaurant Grades A, B, & C

```{r}
rest_inspec %>% 
  count(grade) %>% 
  mutate(grade = fct_reorder(grade, n, .desc = TRUE)) %>% 
  plot_ly(x = ~grade, 
          y = ~n, 
          color = ~grade,
          type = "bar") %>% 
  layout(
    title = "Distribution of Restaurant Grades: A, B, and C",
    xaxis = list(title = "Restaurant Grade"), 
    yaxis = list(title = "Number of Restaurants"))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Boxplot: Graph of Inspection Scores by NYC Boroughs

```{r}
rest_inspec %>% 
  plot_ly(
    y = ~score, 
    color = ~boro, 
    type = "box",
    colors = "Set1") %>% 
  layout(
    title = "Distribution of Restaurant Inspection Scores by NYC Borough",
    xaxis = list(title = "NYC Borough"), 
    yaxis = list(title = "Restaurant Inspection Score"))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Dot Plot: Distribution of Restaurant Grades by Borough

```{r}
inspection_grades = 
  rest_inspec %>%
  mutate(text_label = str_c("Score", score, 'Grade', grade, sep = " ")) %>% 
  plot_ly(
    x = ~ score, 
    y = ~ boro,  
    type = "scatter", 
    mode = "markers",
    color = ~grade, 
    text = ~text_label, 
    alpha = 0.5) %>% 
  layout(
    title = "Distribution of Restaurant Grades by Borough",
    xaxis = list(title = "Restaurant Scores"), 
    yaxis = list(title = "NYC Borough"))

inspection_grades
```

